// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4va1sWSxtegqQzyNGKHiKSt2dPe9zetQ',
    appId: '1:883507267138:web:55f9c71402c61b43220fdb',
    messagingSenderId: '883507267138',
    projectId: 'foodprintuv-91bde',
    authDomain: 'foodprintuv-91bde.firebaseapp.com',
    storageBucket: 'foodprintuv-91bde.appspot.com',
    measurementId: 'G-5PQH19XKZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnZLvI89Zp8SayZgSrsqDgLM1ZTe3FEo',
    appId: '1:883507267138:android:1915ed63419e5dc1220fdb',
    messagingSenderId: '883507267138',
    projectId: 'foodprintuv-91bde',
    storageBucket: 'foodprintuv-91bde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2iKUSvOVlQDy7g5nvZzUPju0pqSAJ76k',
    appId: '1:883507267138:ios:a3a154fcab8f74d4220fdb',
    messagingSenderId: '883507267138',
    projectId: 'foodprintuv-91bde',
    storageBucket: 'foodprintuv-91bde.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2iKUSvOVlQDy7g5nvZzUPju0pqSAJ76k',
    appId: '1:883507267138:ios:a3a154fcab8f74d4220fdb',
    messagingSenderId: '883507267138',
    projectId: 'foodprintuv-91bde',
    storageBucket: 'foodprintuv-91bde.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4va1sWSxtegqQzyNGKHiKSt2dPe9zetQ',
    appId: '1:883507267138:web:f4ab0c1988f5f320220fdb',
    messagingSenderId: '883507267138',
    projectId: 'foodprintuv-91bde',
    authDomain: 'foodprintuv-91bde.firebaseapp.com',
    storageBucket: 'foodprintuv-91bde.appspot.com',
    measurementId: 'G-KG0CFB6J16',
  );

}